version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: Taller1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./dbTaller:/var/lib/postgresql/data
    networks:
      - mi_red1
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - mi_red1
    restart: always

networks:
  mi_red1:
    name: redTaller1 # Nombre real de la red
